apiVersion: v1
kind: Service
metadata:
  name: bridge-api-go
  labels:
    app.kubernetes.io/name: bridge-api-go
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bridge-api-go
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
