apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fhir-openehr-bridge

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/hl7-ie/fhiropenehrbridge-rust
    newTag: latest
