apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fhir-openehr-bridge-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: fhir-openehr-bridge
  source:
    repoURL: https://github.com/hl7-ie/FhirOpenEhrBridge.git
    targetRevision: main
    path: deploy/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fhir-openehr-bridge-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
